version: "3.2"

services:
  go-config:
    image: ixtf/go-config
    restart: always
    volumes:
      - /data/mes-9200/auto/config.yml:/config.yml
    environment:
      CONFIG_PATH: /config.yml
    expose:
      - "1323"
    ports:
      - "1323:1323"
